# Generated by Django 4.0.5 on 2022-07-10 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 10, 20, 37, 9, 451260, tzinfo=utc))),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('startBid', models.DateTimeField()),
                ('endBid', models.DateTimeField()),
            ],
        ),
    ]
