# Generated by Django 4.0.5 on 2022-07-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(max_length=400),
        ),
        migrations.AddField(
            model_name='auction',
            name='category_id',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='categoryId', to='auctions.categories'),
        ),
    ]
