# Generated by Django 4.0.5 on 2022-07-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryId', to='auctions.categories'),
        ),
    ]
