# Generated by Django 4.0.5 on 2022-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_winner_category_id_alter_winner_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
