# Generated by Django 4.0.5 on 2022-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bid_auctionid_alter_bid_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
