# Generated by Django 4.0.5 on 2022-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auction_close_delete_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
