# Generated by Django 4.0.5 on 2022-07-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
