# Generated by Django 4.0.5 on 2022-07-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_watchlist_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='close',
        ),
    ]
